apiVersion: skaffold/v2beta29
kind: Config

metadata:
  name: popular-slides-sk

build:
  artifacts:
    - image: my-flask-app
      context: web-app

    - image: farberg/popular-slides-spark
      context: spark-app

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
