apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: my-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-postgres
  template:
    metadata:
      labels:
        app: my-postgres
    spec:
      volumes:
        - name: init-volume
          configMap:
            name: postgres-deployment-init-configmap
      containers:
        - name: my-postgres
          image: postgres
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/
          env:
            - name: POSTGRES_USER
              value: "myuser"
            - name: POSTGRES_PASSWORD
              value: "mypassword"
            - name: POSTGRES_DB
              value: "coffee-db"
          ports:
            - containerPort: 5432
