apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: coffee-db-kube # Replace with the image tag of your Flask app
          ports:
            - containerPort: 3000
          env:
            - name: FLASK_APP
              value: backend.py
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
            - name: DATABASE_URL
              value: "jdbc:postgresql://my-app-postgres-service:5432/coffee-db"
