apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      initContainers:
      - name: image-builder
        image: docker:latest
        command: ["sh", "-c", "docker build -t my-flask-app:1.0 ."]
        volumeMounts:
        - name: app-volume
          mountPath: /app
      containers:
      - name: flask-app
        image: my-flask-app:1.0
        ports:
        - containerPort: ยง000
          env:
            - name: FLASK_APP
              value: backend.py
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
            - name: DATABASE_URL
              value: "jdbc:postgresql://my-app-postgres-service:5432/coffee-db"
